##### 平均画像生成

In [1]:
import numpy as np
import cv2
import os
import sys

def minsize(s):

    count = 0

    for i in os.listdir(dir):
        im = cv2.imread(dir + i)

        if s > int(im.shape[0]):
            count += 1

            if count == 2:
                print("画像のサイズが統一されていません")
                print("処理を終了します")
                sys.exit()

            s = int(im.shape[0])

    return s

dir = './resize_face/'
num = sum(os.path.isfile(os.path.join(dir, name)) for name in os.listdir(dir))
size = minsize(9999)
pnum = size * size
allarray = np.empty((num, pnum))
pixel = 0 
ave = np.empty(pnum)

for i in range(num):
    img = cv2.imread(dir + "resize_face" + str(i) + ".jpg",cv2.IMREAD_GRAYSCALE)
    allarray[i, :]  =  img.reshape(-1)

for i in range(pnum):
    
    for j in range(num):
        pixel += allarray[j,i]
        
    print(i,pixel,end = "\t")
    
    pixel //= num
    ave[i] = pixel
    
    print(i,ave[i])
    
array = np.reshape(ave, (size, size))
cv2.imwrite('ave_face.jpg', array)

0 16645.0	0 166.0
1 16693.0	1 166.0
2 16290.0	2 162.0
3 16125.0	3 161.0
4 15817.0	4 158.0
5 15186.0	5 151.0
6 13377.0	6 133.0
7 10811.0	7 108.0
8 8596.0	8 85.0
9 6816.0	9 68.0
10 5231.0	10 52.0
11 4054.0	11 40.0
12 3109.0	12 31.0
13 2549.0	13 25.0
14 2233.0	14 22.0
15 2212.0	15 22.0
16 2315.0	16 23.0
17 2289.0	17 22.0
18 2328.0	18 23.0
19 2397.0	19 23.0
20 2413.0	20 24.0
21 2392.0	21 23.0
22 2316.0	22 23.0
23 2236.0	23 22.0
24 2258.0	24 22.0
25 2291.0	25 22.0
26 2275.0	26 22.0
27 2217.0	27 22.0
28 2226.0	28 22.0
29 2265.0	29 22.0
30 2298.0	30 22.0
31 2311.0	31 23.0
32 2326.0	32 23.0
33 2340.0	33 23.0
34 2360.0	34 23.0
35 2385.0	35 23.0
36 2404.0	36 24.0
37 2418.0	37 24.0
38 2419.0	38 24.0
39 2418.0	39 24.0
40 2395.0	40 23.0
41 2395.0	41 23.0
42 2376.0	42 23.0
43 2363.0	43 23.0
44 2366.0	44 23.0
45 2378.0	45 23.0
46 2386.0	46 23.0
47 2371.0	47 23.0
48 2359.0	48 23.0
49 2367.0	49 23.0
50 2381.0	50 23.0
51 2402.0	51 24.0
52 2414.0	52 24.0
53 2424.0	53 24.0
54 2407.0	54 24.0
55 2401.0	55 2

741 10716.0	741 107.0
742 7680.0	742 76.0
743 5336.0	743 53.0
744 3930.0	744 39.0
745 3478.0	745 34.0
746 3086.0	746 30.0
747 2909.0	747 29.0
748 3024.0	748 30.0
749 3212.0	749 32.0
750 3173.0	750 31.0
751 2824.0	751 28.0
752 2570.0	752 25.0
753 2595.0	753 25.0
754 2676.0	754 26.0
755 2769.0	755 27.0
756 2912.0	756 29.0
757 3013.0	757 30.0
758 3043.0	758 30.0
759 2968.0	759 29.0
760 2759.0	760 27.0
761 2525.0	761 25.0
762 2425.0	762 24.0
763 2364.0	763 23.0
764 2313.0	764 23.0
765 2286.0	765 22.0
766 2257.0	766 22.0
767 2255.0	767 22.0
768 2307.0	768 23.0
769 2373.0	769 23.0
770 2364.0	770 23.0
771 2364.0	771 23.0
772 2360.0	772 23.0
773 2359.0	773 23.0
774 2341.0	774 23.0
775 2289.0	775 22.0
776 2212.0	776 22.0
777 2163.0	777 21.0
778 2197.0	778 21.0
779 2157.0	779 21.0
780 2108.0	780 21.0
781 2055.0	781 20.0
782 2011.0	782 20.0
783 1977.0	783 19.0
784 1992.0	784 19.0
785 2022.0	785 20.0
786 2043.0	786 20.0
787 2038.0	787 20.0
788 2080.0	788 20.0
789 2162.0	789 21.0
790 2291.0	790 22.

1366 4122.0	1366 41.0
1367 4125.0	1367 41.0
1368 4149.0	1368 41.0
1369 4145.0	1369 41.0
1370 4140.0	1370 41.0
1371 4128.0	1371 41.0
1372 4101.0	1372 41.0
1373 4113.0	1373 41.0
1374 4149.0	1374 41.0
1375 4174.0	1375 41.0
1376 4233.0	1376 42.0
1377 4493.0	1377 44.0
1378 4692.0	1378 46.0
1379 4807.0	1379 48.0
1380 4901.0	1380 49.0
1381 4859.0	1381 48.0
1382 4521.0	1382 45.0
1383 4353.0	1383 43.0
1384 4171.0	1384 41.0
1385 3974.0	1385 39.0
1386 3684.0	1386 36.0
1387 3631.0	1387 36.0
1388 3844.0	1388 38.0
1389 4044.0	1389 40.0
1390 4469.0	1390 44.0
1391 5292.0	1391 52.0
1392 5593.0	1392 55.0
1393 5762.0	1393 57.0
1394 10922.0	1394 109.0
1395 8072.0	1395 80.0
1396 6238.0	1396 62.0
1397 5320.0	1397 53.0
1398 4251.0	1398 42.0
1399 3480.0	1399 34.0
1400 2846.0	1400 28.0
1401 2679.0	1401 26.0
1402 2692.0	1402 26.0
1403 2667.0	1403 26.0
1404 2813.0	1404 28.0
1405 2704.0	1405 27.0
1406 2928.0	1406 29.0
1407 3610.0	1407 36.0
1408 4459.0	1408 44.0
1409 5137.0	1409 51.0
1410 5648.0	1410 56.0
1411 608

1990 9145.0	1990 91.0
1991 8148.0	1991 81.0
1992 7182.0	1992 71.0
1993 6758.0	1993 67.0
1994 6347.0	1994 63.0
1995 6148.0	1995 61.0
1996 6177.0	1996 61.0
1997 6446.0	1997 64.0
1998 6737.0	1998 67.0
1999 6851.0	1999 68.0
2000 6561.0	2000 65.0
2001 6329.0	2001 63.0
2002 7184.0	2002 71.0
2003 7561.0	2003 75.0
2004 7593.0	2004 75.0
2005 7675.0	2005 76.0
2006 8080.0	2006 80.0
2007 9041.0	2007 90.0
2008 8843.0	2008 88.0
2009 7932.0	2009 79.0
2010 6534.0	2010 65.0
2011 5779.0	2011 57.0
2012 5614.0	2012 56.0
2013 5780.0	2013 57.0
2014 6448.0	2014 64.0
2015 6862.0	2015 68.0
2016 7411.0	2016 74.0
2017 7855.0	2017 78.0
2018 8359.0	2018 83.0
2019 8543.0	2019 85.0
2020 8425.0	2020 84.0
2021 8171.0	2021 81.0
2022 7965.0	2022 79.0
2023 7791.0	2023 77.0
2024 7749.0	2024 77.0
2025 7780.0	2025 77.0
2026 7865.0	2026 78.0
2027 7998.0	2027 79.0
2028 8187.0	2028 81.0
2029 8413.0	2029 84.0
2030 8541.0	2030 85.0
2031 8554.0	2031 85.0
2032 8520.0	2032 85.0
2033 8436.0	2033 84.0
2034 8192.0	2034 81.0
2035 7639.

2740 13107.0	2740 131.0
2741 12063.0	2741 120.0
2742 14501.0	2742 145.0
2743 17637.0	2743 176.0
2744 19271.0	2744 192.0
2745 19404.0	2745 194.0
2746 19292.0	2746 192.0
2747 19340.0	2747 193.0
2748 19225.0	2748 192.0
2749 18535.0	2749 185.0
2750 16701.0	2750 167.0
2751 14768.0	2751 147.0
2752 13254.0	2752 132.0
2753 12344.0	2753 123.0
2754 13282.0	2754 132.0
2755 15068.0	2755 150.0
2756 16993.0	2756 169.0
2757 17693.0	2757 176.0
2758 17640.0	2758 176.0
2759 17509.0	2759 175.0
2760 17053.0	2760 170.0
2761 16436.0	2761 164.0
2762 16019.0	2762 160.0
2763 15414.0	2763 154.0
2764 14671.0	2764 146.0
2765 14014.0	2765 140.0
2766 13279.0	2766 132.0
2767 12392.0	2767 123.0
2768 11655.0	2768 116.0
2769 11331.0	2769 113.0
2770 11147.0	2770 111.0
2771 11061.0	2771 110.0
2772 10271.0	2772 102.0
2773 9663.0	2773 96.0
2774 9269.0	2774 92.0
2775 8955.0	2775 89.0
2776 9243.0	2776 92.0
2777 8937.0	2777 89.0
2778 8526.0	2778 85.0
2779 8930.0	2779 89.0
2780 8864.0	2780 88.0
2781 8200.0	2781 82.0
2782 7633.

3365 12211.0	3365 122.0
3366 12473.0	3366 124.0
3367 12152.0	3367 121.0
3368 11973.0	3368 119.0
3369 12912.0	3369 129.0
3370 15665.0	3370 156.0
3371 18407.0	3371 184.0
3372 19854.0	3372 198.0
3373 20328.0	3373 203.0
3374 21119.0	3374 211.0
3375 21586.0	3375 215.0
3376 22064.0	3376 220.0
3377 22211.0	3377 222.0
3378 22229.0	3378 222.0
3379 22104.0	3379 221.0
3380 21847.0	3380 218.0
3381 21612.0	3381 216.0
3382 21520.0	3382 215.0
3383 21513.0	3383 215.0
3384 21493.0	3384 214.0
3385 21446.0	3385 214.0
3386 21598.0	3386 215.0
3387 21589.0	3387 215.0
3388 21560.0	3388 215.0
3389 21493.0	3389 214.0
3390 21441.0	3390 214.0
3391 21444.0	3391 214.0
3392 21508.0	3392 215.0
3393 21568.0	3393 215.0
3394 21671.0	3394 216.0
3395 21922.0	3395 219.0
3396 22166.0	3396 221.0
3397 22278.0	3397 222.0
3398 22288.0	3398 222.0
3399 22224.0	3399 222.0
3400 22025.0	3400 220.0
3401 21799.0	3401 217.0
3402 21348.0	3402 213.0
3403 21013.0	3403 210.0
3404 20680.0	3404 206.0
3405 20612.0	3405 206.0
3406 20753.0	340

4115 22579.0	4115 225.0
4116 22532.0	4116 225.0
4117 22562.0	4117 225.0
4118 22477.0	4118 224.0
4119 22310.0	4119 223.0
4120 22166.0	4120 221.0
4121 22003.0	4121 220.0
4122 21706.0	4122 217.0
4123 21394.0	4123 213.0
4124 20955.0	4124 209.0
4125 20634.0	4125 206.0
4126 20193.0	4126 201.0
4127 19851.0	4127 198.0
4128 19676.0	4128 196.0
4129 19668.0	4129 196.0
4130 19737.0	4130 197.0
4131 19822.0	4131 198.0
4132 20011.0	4132 200.0
4133 20274.0	4133 202.0
4134 20655.0	4134 206.0
4135 21012.0	4135 210.0
4136 21280.0	4136 212.0
4137 21354.0	4137 213.0
4138 21028.0	4138 210.0
4139 20506.0	4139 205.0
4140 19549.0	4140 195.0
4141 18748.0	4141 187.0
4142 17896.0	4142 178.0
4143 17284.0	4143 172.0
4144 16765.0	4144 167.0
4145 16416.0	4145 164.0
4146 16249.0	4146 162.0
4147 16139.0	4147 161.0
4148 16082.0	4148 160.0
4149 16111.0	4149 161.0
4150 16175.0	4150 161.0
4151 16257.0	4151 162.0
4152 16298.0	4152 162.0
4153 16328.0	4153 163.0
4154 16440.0	4154 164.0
4155 16559.0	4155 165.0
4156 16680.0	415

4785 20268.0	4785 202.0
4786 20318.0	4786 203.0
4787 20382.0	4787 203.0
4788 20401.0	4788 204.0
4789 20253.0	4789 202.0
4790 20028.0	4790 200.0
4791 19799.0	4791 197.0
4792 19565.0	4792 195.0
4793 19268.0	4793 192.0
4794 18840.0	4794 188.0
4795 18449.0	4795 184.0
4796 17920.0	4796 179.0
4797 17538.0	4797 175.0
4798 17023.0	4798 170.0
4799 16446.0	4799 164.0
4800 15805.0	4800 158.0
4801 15263.0	4801 152.0
4802 14922.0	4802 149.0
4803 14744.0	4803 147.0
4804 14727.0	4804 147.0
4805 14773.0	4805 147.0
4806 14833.0	4806 148.0
4807 14867.0	4807 148.0
4808 14839.0	4808 148.0
4809 14756.0	4809 147.0
4810 14689.0	4810 146.0
4811 14657.0	4811 146.0
4812 14608.0	4812 146.0
4813 14743.0	4813 147.0
4814 14968.0	4814 149.0
4815 15372.0	4815 153.0
4816 15987.0	4816 159.0
4817 16552.0	4817 165.0
4818 16992.0	4818 169.0
4819 17426.0	4819 174.0
4820 17713.0	4820 177.0
4821 17617.0	4821 176.0
4822 17577.0	4822 175.0
4823 17729.0	4823 177.0
4824 17700.0	4824 177.0
4825 17362.0	4825 173.0
4826 16966.0	482

5490 13873.0	5490 138.0
5491 13988.0	5491 139.0
5492 13782.0	5492 137.0
5493 13593.0	5493 135.0
5494 15208.0	5494 152.0
5495 14100.0	5495 141.0
5496 13513.0	5496 135.0
5497 14533.0	5497 145.0
5498 15245.0	5498 152.0
5499 15624.0	5499 156.0
5500 16276.0	5500 162.0
5501 16990.0	5501 169.0
5502 18078.0	5502 180.0
5503 18359.0	5503 183.0
5504 18540.0	5504 185.0
5505 18828.0	5505 188.0
5506 19296.0	5506 192.0
5507 19806.0	5507 198.0
5508 19998.0	5508 199.0
5509 19991.0	5509 199.0
5510 20047.0	5510 200.0
5511 20272.0	5511 202.0
5512 20423.0	5512 204.0
5513 20482.0	5513 204.0
5514 20678.0	5514 206.0
5515 20867.0	5515 208.0
5516 20799.0	5516 207.0
5517 20648.0	5517 206.0
5518 20442.0	5518 204.0
5519 20334.0	5519 203.0
5520 20196.0	5520 201.0
5521 20077.0	5521 200.0
5522 19953.0	5522 199.0
5523 19790.0	5523 197.0
5524 19581.0	5524 195.0
5525 19413.0	5525 194.0
5526 19246.0	5526 192.0
5527 19058.0	5527 190.0
5528 18772.0	5528 187.0
5529 18393.0	5529 183.0
5530 17910.0	5530 179.0
5531 17432.0	553

6145 12920.0	6145 129.0
6146 13494.0	6146 134.0
6147 13859.0	6147 138.0
6148 14211.0	6148 142.0
6149 14313.0	6149 143.0
6150 15651.0	6150 156.0
6151 16549.0	6151 165.0
6152 17287.0	6152 172.0
6153 17616.0	6153 176.0
6154 17800.0	6154 178.0
6155 16958.0	6155 169.0
6156 16157.0	6156 161.0
6157 15956.0	6157 159.0
6158 15932.0	6158 159.0
6159 15844.0	6159 158.0
6160 15954.0	6160 159.0
6161 16052.0	6161 160.0
6162 16017.0	6162 160.0
6163 16080.0	6163 160.0
6164 16268.0	6164 162.0
6165 16527.0	6165 165.0
6166 16818.0	6166 168.0
6167 17119.0	6167 171.0
6168 17673.0	6168 176.0
6169 18339.0	6169 183.0
6170 18849.0	6170 188.0
6171 18983.0	6171 189.0
6172 18926.0	6172 189.0
6173 18940.0	6173 189.0
6174 19027.0	6174 190.0
6175 19120.0	6175 191.0
6176 19203.0	6176 192.0
6177 19160.0	6177 191.0
6178 18942.0	6178 189.0
6179 18587.0	6179 185.0
6180 18181.0	6180 181.0
6181 17879.0	6181 178.0
6182 17452.0	6182 174.0
6183 16917.0	6183 169.0
6184 16440.0	6184 164.0
6185 16180.0	6185 161.0
6186 15883.0	618

True

##### 平均画像生成（コメントあり）

In [5]:
import numpy as np
import cv2
import os

# 関数定義（画像のサイズを取得する）
def minsize(s):
    
    count = 0
    # ファイル分ループ
    for i in os.listdir(dir):
        # 画像読み込み
        im = cv2.imread(dir + i)
        
        # もし s(9999) より画像の縦サイズが小さかったら
        if s > int(im.shape[0]):
            # カウントにプラス１
            count += 1
            
            # もしカウントが２ならば動く処理
            if count == 2:
                print("画像のサイズが統一されていません")
                print("処理を終了します")
                # 処理を終了させる
                sys.exit()
            # s に縦サイズを代入
            s = int(im.shape[0])
            
    # 結果を返す
    return s

# ファイル数を取得するフォルダの指定
dir = '../Production_exercise/cv/resize_ok/'
# ファイル数を取得 num に格納
num = sum(os.path.isfile(os.path.join(dir, name)) for name in os.listdir(dir))
# 関数呼び出し（値は9999）
size = minsize(9999)
# size * size の総画素数を pnum に格納
pnum = size * size
# 縦　ファイル数 num 　：　横　総画素数 pnum 　の二次元配列を生成
allarray = np.empty((num, pnum))
# 計算の答え置き
pixel = 0
# 平均画素数格納用の長さ pnum の一次元配列を生成
ave = np.empty(pnum)

# ファイル数分ループ
for i in range(num):
    # 画像をグレースケール化 ＆ 読み込み
    img = cv2.imread(dir + "resize_face" + str(i) + ".jpg",cv2.IMREAD_GRAYSCALE)
    # 多次元配列である img を　reshape(-1) で一次元配列に変換
    # 二次元配列の i 番目に格納   
    allarray[i, :]  =  img.reshape(-1)

    
    
    
# 総画素数文ループ
for i in range(pnum):
    
    # ファイル分ループ
    for j in range(num):
        # 二次元配列の縦の行の値のすべてを加算 pixel に格納
        pixel = pixel + allarray[j,i]
    
    # 加算されているかの確認
    print(i,pixel,end = "\t")
    
    # pixel をファイル数で割る（小数点切り捨て）
    pixel //= num
    # 一次元配列の i 番目に格納
    ave[i] = pixel
    
    # 割れているかの確認
    print(i,ave[i])
    
# 一次元配列を size * size の多次元配列 array に格納
array = np.reshape(ave, (size, size))
# 保存
cv2.imwrite('ave_favce.jpg', array)

[[ 42  45  48 ... 139 139 139]
 [ 39  43  45 ... 139 139 139]
 [ 37  40  43 ... 139 139 139]
 ...
 [ 27  27  27 ...  41  44  45]
 [ 28  27  26 ...  41  44  45]
 [ 27  27  26 ...  40  43  45]]
[[199 201 202 ...  31  93 146]
 [197 200 197 ...  25  79 137]
 [196 198 192 ...  23  59 110]
 ...
 [ 17  15  13 ...  42  32  30]
 [ 17  15  12 ...  39  30  29]
 [ 17  15  12 ...  36  28  27]]
[[ 19  19  21 ... 166 167 166]
 [ 19  18  21 ... 168 167 165]
 [ 18  18  20 ... 167 167 166]
 ...
 [  8   9   9 ...  23  33  40]
 [ 10   9   7 ...  20  27  35]
 [  9  10  11 ...  15  20  27]]
[[206 183 114 ...  72 149 190]
 [204 177 105 ...  49 110 176]
 [203 168  91 ...  23  63 144]
 ...
 [ 14  14  14 ...  16  14  12]
 [ 13  13  12 ...  16  14  13]
 [ 12  12  11 ...  15  12  10]]
[[224 204 183 ...  21  21  21]
 [223 210 201 ...  21  21  21]
 [233 225 225 ...  20  20  21]
 ...
 [ 16  18  25 ...  28  32  34]
 [ 19  17  28 ...  27  30  31]
 [ 21  15  25 ...  26  29  30]]
[[ 95  90  93 ...  25  24  26]
 [ 97 101

IndexError: index 150 is out of bounds for axis 0 with size 150